services:
  frontend:
    build: ./reactjs
    ports:
      - 5123:80
    environment:
      API_BASEURL: http://localhost:4567/api/v1

  backend:
    build: ./expressjs
    ports:
      - 5456:4567
    environment:
      DB_CONN_STRING: "mongodb://mongo:5789/mern-stack-template"
      APP_PORT: "4567"
      TOKEN_SKY: "VanityIsMyFavouriteSin"
      TOKEN_ALGO: "HS384"
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mern-mongo
    ports:
      - 5789:27017
    volumes:
      - mongodb_mst:/data/db
    environment:
      MONGO_INITDB_DATABASE: mern-stack-template

volumes:
  mongodb_mst:
